### ISSUE TITLE
warning: must specify at least one argument for '...' parameter of variadic macro [-Wgnu-zero-variadic-macro-arguments]

### ISSUE THREAD

**Issue by WSoptics** [woboq/verdigris#7] opened 2017-08-01 14:01 UTC
Using gcc 6.3 and clang 4.0.1 with -Wpedantic, W_SIGNAL and W_OBJECT_IMPL produce the warning above
[test.zip](https://github.com/woboq/verdigris/files/1190770/test.zip)

**Comment by WSoptics** [comment] 2017-08-01 14:05
For W_OBJECT_IMPL this could be easily handled by passing the template arguments like this
W_OBJECT_IMPL((A<U,V>), (template <typename U, typename V)), as this would remove the need of a variadic template while beeing just as easily understandable. The only problem would be, that this is a breaking change.

**Comment by ogoffart** [comment] 2017-08-03 09:05
I guess i'll need to add the right pragma to disable this warning. That would be the easier.

(btw, the zip file is empty)

**Comment by fiesh** [comment] 2017-08-24 10:06
I'm not sure that a pragma will help, unless once deactivates the warning for all files that include the header file, which seems undesirable.  The problem is that with the preprocessor, the warnings are normally produced when the macro is invoked, not where it's defined.

**Comment by suy** [comment] 2017-08-24 13:05
Most compilers allow to push an warning to an ignore stack, and pop it back to the original state. You just push and pop before and after your problematic line, and users don't see it.

**Comment by fiesh** [comment] 2017-08-24 13:07
Yes, but like I said, in my experience this cannot be done with macros because their warnings are generated upon invocation, not definition of the macro.  Or maybe I am missing the point entirely.

**Comment by ogoffart** [comment] 2017-08-26 08:27
@fiesh: This can be done in macro (using _Pragma)

There is even helper in qt (QT_WARNING_PUSH / POP,  QT_WARNING_DISABLE_GCC)
(the definition of Q_OBJECT macro in qobjectdefs.h shows an example using them)

**Comment by fiesh** [comment] 2017-08-26 10:15
Oh I see, the deactivation is done within the macro itself, not around it.  That might work, thanks!

**Comment by ogoffart** [comment] 2018-01-04 22:34
Should be fixed fixed with commit ed35968

**Closed by ogoffart** 2018-01-04 22:34 UTC
